apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.pool }}
spec:
  ipAddressPools:
  - {{ .Values.pool }}
  {{- if .Values.interface }}
  interfaces:
  - {{ .Values.interface }}
  {{- end }}
