namespace: argocd

sources:
- name: apps
  type: apps
  repo: https://github.com/rjchicago/monorepo.git
  branch: main
  path: k8s/apps
  sync: false
  envs:
  - local
  appEnvs:
  - test
- name: core
  type: core
  repo: https://github.com/rjchicago/monorepo.git
  branch: main
  path: k8s/core
  sync: false
  envs:
  - local

destinations:
- cluster: local
  server: https://kubernetes.default.svc
  env: local
