{{- if .Capabilities.APIVersions.Has "traefik.containo.us/v1alpha1" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: {{ .Values.ingress.match }}
    services:
    - kind: Service
      name: {{ .Values.chartmuseum.service.servicename }}
      port: {{ .Values.chartmuseum.service.externalPort }}
      passHostHeader: true
{{- end }}
