{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
{{- range $secret := .Values.secrets }}
  {{ base $secret.path }}: {{ $.Files.Get $secret.path }}
{{- end }}
{{- end }}
